Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VolleyDamois.Models;
using VolleyDamois.Models.Builder;
using VolleyDamois.Models.ViewModel;

namespace VolleyDamois.Controllers
{
    public class MatchesController : Controller
    {
        private readonly VolleyDamoisDbContext _context;

        public MatchesController(VolleyDamoisDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index() {
            ViewModelMatches vmMatches = new ViewModelMatches();
            vmMatches.FormatMatches(await getMatches());
            return View(vmMatches);
        }

       

        // GET: Matches/Details/5
        public async Task<IActionResult> Result()
        {
            ViewModelMatches vmMatches = new ViewModelMatches();
            vmMatches.FormatMatches(await getMatches());
            return View(vmMatches);
        }


        [Authorize(Roles="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateMatches(List<ViewModelMatchesToUpdate> vmMtu) {

            List<Match> matches = await getMatches();
            foreach (ViewModelMatchesToUpdate vm in vmMtu)
            {
                Match currentMatch = matches.Where(m => m.Id == vm.Id).First();
                CheckValue(vm, currentMatch);
            }
            _context.SaveChanges();
            return Redirect("Result");
        }

        private static void CheckValue(ViewModelMatchesToUpdate vm, Match currentMatch)
        {
            if (vm.Set11 > 0) currentMatch.Team1Set1 = vm.Set11; else currentMatch.Team1Set1 = 0;
            if (vm.Set12 > 0) currentMatch.Team1Set2 = vm.Set12; else currentMatch.Team1Set2 = 0;
            if (vm.Set21 > 0) currentMatch.Team2Set1 = vm.Set21; else currentMatch.Team2Set1 = 0;
            if (vm.Set22 > 0) currentMatch.Team2Set2 = vm.Set22; else currentMatch.Team2Set2 = 0;
        }

        public async Task<IActionResult> Classement()
        {
            ClassementPoule classementPoule = new ClassementPoule(await getMatches(), await _context.Poules.Include(p => p.Teams).ToListAsync());
            ClassementDay2 classementDay2 = new ClassementDay2(await getMatches());
            ViewModelClassement vmClassement = new ViewModelClassement();
            vmClassement.classementDay1 = classementPoule.createClassementPoules();
            vmClassement.classementDay2 = classementDay2.MakeClassement();
            return View(vmClassement);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateMatchDay2()
        {
            ClassementPoule classementPoule = new ClassementPoule(await getMatches(),_context.Poules.Include(p => p.Teams).ToList());
            List<Level>levels = _context.Level.ToList();
            MatchBuilderDay1 mbuild = new MatchBuilderDay1(levels.Where(l => l.LevelConfrotation == LevelMatch.Seizième).First());
            List<Dictionary<Team, int[]>> poules = classementPoule.createClassementPoules();
            
            MatchBuilderDay2 day2Builder = new MatchBuilderDay2(await _context.Level.Where(l => l.LevelConfrotation == LevelMatch.Seizième).FirstAsync());
            List<Match> matchDay2 = day2Builder.createMatchesforDay2(poules,
                _context.Field.Include(f => f.FieldCategory).ToList(),
                _context.State.Where(s => s.StateMatch == StateMatch.planned).First());
            _context.Matches.AddRange(matchDay2);
            _context.SaveChanges();
            return Redirect("Classement");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFinalsMatch()
        {
            
            return Redirect("Classement");
        }

        private Task<List<Match>> getMatches()
        {
            return _context.Matches.Include(m => m.Team1)
                .Include(m => m.Team2)
                .Include(m => m.Arbitre)
                .Include(m => m.Terrain)
                .Include(m => m.State)
                .Include(m => m.level)
                .ToListAsync();
        }
    }


}

Controllers/PoulesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VolleyDamois.Models;

namespace VolleyDamois.Controllers
{
    public class PoulesController : Controller
    {
        private readonly VolleyDamoisDbContext _context;

        public PoulesController(VolleyDamoisDbContext context)
        {
            _context = context;
        }

        // GET: Poules
        public async Task<IActionResult> Index()
        {
            return View(await _context.Poules
                .Include( p => p.Teams).ThenInclude(t => t.Category)
                .ToListAsync());
        }

        // GET: Poules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poule = await _context.Poules
                .FirstOrDefaultAsync(m => m.id == id);
            if (poule == null)
            {
                return NotFound();
            }

            return View(poule);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create()
        {
            PouleBuilder builderPoule = new PouleBuilder();
            MatchBuilderDay1 builderMatch = new MatchBuilderDay1(_context.Level.Where(l => l.LevelConfrotation == LevelMatch.Poule).First());
            var teamsRequest = _context.Team.Include(x => x.Players).Include(x => x.Category);
            IList<Team> teams = teamsRequest.ToList();
            IList<Poule> poules = builderPoule.createPoulesForEachCategories(teams);
            foreach (Poule poul in poules)
            {
                _context.Poules.Add(poul);
                _context.SaveChanges();
            }

            _context.Matches.AddRange(
                builderMatch.createMatchesforPoule(
                    _context.Poules.ToList(),
                    _context.Field.Where(f => f.FieldCategory.Category == Category.Nationale).ToList(),
                    _context.State.Where(s => s.StateMatch == StateMatch.planned).First())
            );
            _context.SaveChanges();
            

            

            return RedirectToAction(nameof(Index));
        }

        // POST: Poules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name")] Poule poule)
        {
            return View();
        }

        // GET: Poules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poule = await _context.Poules.FindAsync(id);
            if (poule == null)
            {
                return NotFound();
            }
            return View(poule);
        }

        // POST: Poules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name")] Poule poule)
        {
            if (id != poule.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(poule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PouleExists(poule.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(poule);
        }

        // GET: Poules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poule = await _context.Poules
                .FirstOrDefaultAsync(m => m.id == id);
            if (poule == null)
            {
                return NotFound();
            }

            return View(poule);
        }

        // POST: Poules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var poule = await _context.Poules.FindAsync(id);
            _context.Poules.Remove(poule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PouleExists(int id)
        {
            return _context.Poules.Any(e => e.id == id);
        }
    }
}

Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VolleyDamois.Models;

namespace VolleyDamois.Controllers
{
    public class TeamsController : Controller
    {
        private readonly VolleyDamoisDbContext _context;

        public TeamsController(VolleyDamoisDbContext context)
        {
            _context = context;
        }

        // GET: Teams
        public async Task<IActionResult> Index(String search = "")
        {
            @ViewBag.CurrentFilter = search;
            var teamList = await _context.Team
                .Include(t=> t.Players)
                .Include(t=>t.Category)
                .ToListAsync();
            if(search != "" && search != null){
                 teamList = teamList.Where(t => t.TeamName.ToLower().Contains(search.ToLower())).ToList();
            }
            return View(teamList);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .Include(t=> t.Players).ThenInclude(p => p.Sex)
                .Include(t => t.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamName,Category,Players")] Team team)
        {
            team.Category = _context.Categories.Where(c => c.Category == team.Category.Category).First();
            team.Players.ForEach( p => p.Sex = _context.Sex.Where(s => s.Sexe == p.Sex.Sexe).First());
            if (ModelState.IsValid)
            {
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            

            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("TeamName")] Team team)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Team.FindAsync(id);
            _context.Team.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Produces("application/json")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchName()
        {
            string term = HttpContext.Request.Query["searchName"].ToString();
            var list = await _context.Team.Where(t => t.TeamName.Contains(term)).Select(t => t.TeamName).ToListAsync();
            return Ok(list);
        }

        private bool TeamExists(int id)
        {
            return _context.Team.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VolleyDamois</title>
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/jqueryui/jquery-ui.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <script src="~/jqueryui/jquery-ui.js"></script>
        <link href="~/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Matches" asp-action="Index">Horaires</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Poules" asp-action="Index">Poules</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Teams" asp-action="Index">Equipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Matches" asp-action="Result">Résultats</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Matches" asp-action="Classement">Classement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Teams" asp-action="Create">S'inscrire</a>
                    </li>
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="border-top footer text-muted">
    <div class="container bg-dark text-white">
        &copy; 2020 - VolleyDamois - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<environment include="Development">
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/jqueryui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="~/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/jqueryui/jquery-ui.min.js" asp-append-version="true"></script>
</environment>
@RenderSection("Scripts", required: false)
</body>
</html>